# Generated by Django 4.0.1 on 2022-02-08 09:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('snippets', '0002_alter_snippet_options'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='snippet',
            options={'ordering': ('created',), 'verbose_name': 'Сниппет', 'verbose_name_plural': 'Сниппеты'},
        ),
    ]
