# Generated by Django 4.0.1 on 2022-01-18 11:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0002_community'),
    ]

    operations = [
        migrations.AddField(
            model_name='person',
            name='communities',
            field=models.ManyToManyField(to='app1.Community'),
        ),
    ]
