# Generated by Django 4.0.1 on 2022-01-18 12:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0005_person_age_alter_person_communities'),
    ]

    operations = [
        migrations.AlterField(
            model_name='person',
            name='age',
            field=models.SmallIntegerField(default=None),
        ),
    ]
