# Generated by Django 4.0.1 on 2022-01-24 12:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0006_alter_person_age'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='community',
            options={'verbose_name': 'Сообщество', 'verbose_name_plural': 'Сообщества'},
        ),
        migrations.AlterModelOptions(
            name='person',
            options={'verbose_name': 'Персона', 'verbose_name_plural': 'Персоны'},
        ),
        migrations.AlterModelOptions(
            name='sex',
            options={'verbose_name': 'Пол', 'verbose_name_plural': 'Пол'},
        ),
    ]
